# Generated by Django 3.1.7 on 2021-03-09 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='puntaje',
            field=models.IntegerField(max_length=50),
        ),
    ]
